# Generated by Django 3.0.6 on 2020-05-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('mailto', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('dtime', models.DateTimeField()),
            ],
        ),
    ]
