# Generated by Django 3.0.6 on 2020-05-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_auto_20200522_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeat_type',
            name='repeat_name',
            field=models.CharField(max_length=20, verbose_name='Частота повторения'),
        ),
    ]
