# Generated by Django 3.0.6 on 2020-05-27 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_auto_20200522_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repeat_type',
            options={'verbose_name': 'Частота повторения', 'verbose_name_plural': 'Частота повторения'},
        ),
        migrations.AlterField(
            model_name='snd',
            name='repeat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sender.Repeat_type', verbose_name='Частота повторения'),
        ),
    ]
